### ISSUE TITLE
Unable to compile the project with Testzeus-1.0.1.jar file (TestZeus base file is missing in jar file)

### ISSUE THREAD

**Issue by SivasankaranGIT** [TestZeus/TestZeus#11]
I have downloaded the TestZeus jar file and imported into my project but I am unable to run the project as the TestZeus.base file is missing in the downloaded jar file. I even tried the same with pom.xml MVN dependency file but still the same files are missing in it. Kindly resolve it.

**Comment by smilinrobin** [comment]
Hi @SivasankaranGIT ,

Kindly try out the solution mentioned here: https://github.com/TestZeus/TestZeus/commit/d35f1ec5c52594aab23c6e765ddb01a89a01e565#commitcomment-78946563 . 

And thanks for trying out TestZeus. 🙏

**Comment by SivasankaranGIT** [comment]
Hi @smilinrobin thanks for your quick response. I tried the given solution (cleared the said path and ran mvn compile) but still the missing files are not download as you can see in the attached screenshot.
<img width="687" alt="Missing File" src="https://user-images.githubusercontent.com/111723343/186328344-6d3edfb7-ff9e-4873-95c4-d1d3735040b9.png">

**Comment by smilinrobin** [comment]
Hi @SivasankaranGIT , I've been able to replicate the problem and while I am looking for a solution, here's what worked for me : 
Kindly import the [TestZeus archetype ](https://github.com/TestZeus/testzeus-archetype.git) into the same workspace and perform a project CLEAN. This should solve the dependency issue.

**Comment by smilinrobin** [comment]
Hello @SivasankaranGIT . The issue for "testzeus.base not found" should be resolved now as we have : 

1. Updated the folder structures for both TestZeus Maven dependency and the corresponding framework. 
2. Cleaned up Base Test class
3. Updated the TestZeus maven dependency version to 1.0.2

If you would simply like to fix the issue, you can just update the maven dependency version for TestZeus to 1.0.2 in your POM file. Alternatively, you can pull a new copy of the framework itself from [here](https://github.com/TestZeus/TestZeus)
Can you please try it out and let us know of your feedback ?

**Comment by SivasankaranGIT** [comment]
Thank you @smilinrobin . Sure, will try again today with the latest changes and will let you know.

**Comment by gneumann2** [comment]
Hi @SivasankaranGIT, can you please confirm that this issue is now fixed? Thanks! Georg

**Comment by SivasankaranGIT** [comment]
Hi,

Yes, it is working. Thank you very much.

Regards,
Siva.
