### ISSUE TITLE
Facing issue in Test Zeus App Launcher

### ISSUE THREAD

**Issue by rashibajaj12** [TestZeus/TestZeus#14]
When i am trying to launch Any App(Example Account) using app Launcher that step is failing. On close Debugging I found that "Response from App Launcher for 9 dot icons" is coming however in next step while trying to form the Account URL its empty. So in Framework "GetSFApps.class" , the object URL is basically returning empty.I am unable to proceed further.

lightningloginpage.applauncher("Accounts");

**Comment by smilinrobin** [comment]
Hi @rashibajaj12 , 
Thanks for reaching out. Can you please try it as per the [notes ](http://testzeus.com/#:~:text=pb.appLauncher(%22Account%22)%3B) here? 

And update the code to below:
`lightningloginpage.applauncher("Account");`

**Comment by smilinrobin** [comment]
@rashibajaj12 - We have identified breaking issues in the recent API responses, so we will update the code and try to do a patch fix release for the codebase

**Comment by smilinrobin** [comment]
Hi @rashibajaj12 , this should be resolved as well with the latest update to the [TestZeus Maven dependency](https://s01.oss.sonatype.org/index.html#nexus-search;quick~testzeus). Kindly check it out.

**Comment by smilinrobin** [comment]
@rashibajaj12  - Can we close this issue ?

**Comment by rashibajaj12** [comment]
This can be closed too.Thanks

**Comment by smilinrobin** [comment]
thanks for the confirmation.
