### ISSUE TITLE
Getting error " Missing property in path $['layouts']['Account']"  while trying to do uiApiParser for case object

### ISSUE THREAD

**Issue by rashibajaj12** [TestZeus/TestZeus#15]
Getting error " Missing property in path $['layouts']['Account']"  while trying to do uiApiParser for case object
This error is coming from "CODE-	caseListPage.uiApiParser(recordid);"
Error- com.jayway.jsonpath.PathNotFoundException: Missing property in path $['layouts']['Account']
While debugging found that uiApiParser method,inside that sectionGetter() is there.there its set as  String sectionspath = "$.layouts.Account..sections";
So its unable to recognize path.Please help

**Comment by smilinrobin** [comment]
Sure @rashibajaj12 . Can you please double check the path to "sections" tag under the "Account" node in the JSON response? We are using UI API Parser to get the sections . Also, if you can post the JSON response, then we can debug it more easily.

**Comment by rashibajaj12** [comment]
It looks like below-
![image](https://github.com/TestZeus/TestZeus/assets/137148895/ec74b4b7-cc89-4e09-b33d-8c8430b2d058)

**Comment by rashibajaj12** [comment]
Any solutions here in above issue?

**Comment by rashibajaj12** [comment]
Hey @smilinrobin Is it possible to make changes in Test Zeus jar file and upload it again here..I m having some issues in updating the jar file in maven dependencies

**Comment by smilinrobin** [comment]
Yes , it can be done; but it would take a while.

**Comment by smilinrobin** [comment]
Hi @rashibajaj12 , we have updated the parametrized method for case object and updated the Maven dependency to 1.0.4. Kindly update your POM and check out the changes.

**Comment by rashibajaj12** [comment]
hi @smilinrobin  I have 2 questions regarding framework-
1)If my object have many record types for ex. Take "Case" object then when uiApiParser method doesnot get the recod type "Label".Does it mean i have to automate it as normal selenium script then by capturing page and locating record type elements and then clicking them?
2)The uiApiParser method wrks if there is an existing record id.For ex in my test case i need to directly create case object without using an existing id ,is there any way to do so? like for using formValueFiller i need to get labels for that object.How do i get it if i dont have any existing record id?
Thanks for ur support .

**Comment by smilinrobin** [comment]
Hi @rashibajaj12 - Can we close this issue as I have moved the last question to a new issue ID? https://github.com/TestZeus/TestZeus/issues/16

**Comment by rashibajaj12** [comment]
Sure .And Thanks for your quick responses.

**Comment by smilinrobin** [comment]
thanks for the confirmation
