### ISSUE TITLE
Record types and existing record ids

### ISSUE THREAD

**Issue by smilinrobin** [TestZeus/TestZeus#16]
hi @smilinrobin  I have 2 questions regarding framework-
1)If my object have many record types for ex. Take "Case" object then when uiApiParser method doesnot get the recod type "Label".Does it mean i have to automate it as normal selenium script then by capturing page and locating record type elements and then clicking them?
2)The uiApiParser method wrks if there is an existing record id.For ex in my test case i need to directly create case object without using an existing id ,is there any way to do so? like for using formValueFiller i need to get labels for that object.How do i get it if i dont have any existing record id?
Thanks for ur support .

_Originally posted by @rashibajaj12 in https://github.com/TestZeus/TestZeus/issues/15#issuecomment-1647807015_

**Comment by smilinrobin** [comment]
1. We do get record types , but we dont make successive calls to fetch the details from UI API.
2. Currently uiApiParser is implemented in such a way that it targets a certain record ID. So , in the future we might augment this approach with just an object name.

**Comment by rashibajaj12** [comment]
So for point number 1 ,This type of below page how do we select right record type and proceed to next main page?
![image](https://github.com/TestZeus/TestZeus/assets/137148895/1e9ad516-fddc-48f9-91fe-9ee3dd6974e4)

**Comment by rashibajaj12** [comment]
Any update on above query?

**Comment by smilinrobin** [comment]
Thanks for the patience. Currently we do not support record type selection directly, however [PageBase](https://github.com/TestZeus/testzeus-archetype/blob/master/src/main/java/testzeus/base/PageBase.java) has multiple types of clicks and interactions (including JS clicks and SFClick) which can be used for selecting the record type.

**Comment by smilinrobin** [comment]
Hi @rashibajaj12 , we've added the above issues to the roadmap here: https://github.com/TestZeus/TestZeus/projects/1 . Should we close this issue?

**Comment by rashibajaj12** [comment]
Sure @smilinrobin  We can close this.Thanks for your support

**Comment by smilinrobin** [comment]
Closing the issue as it has been moved to backlog.
