### ISSUE TITLE
Can not  find testzeus.base.* files

### ISSUE THREAD

**Issue by rachanakushwaha** [TestZeus/TestZeus#9]
Hi Robin,

I have imported this framework and I could not find testzeus.base.PageBase ,testzeus.base.GetApps ,testzeus.base.HTTPClientWrapper ,
Could you please share these files.

Thanks
Rachana

**Comment by robinguptaprovar** [comment]
Hi @rachanakushwaha - (Assuming you are going with [Option B](https://github.com/TestZeus/TestZeus#b-using-testzeus-as-a-dependency-in-your-existing-test-automation-framework)) If you import the maven dependency (https://search.maven.org/artifact/com.testzeus/Test_Zeus) and do a clean install, Maven will download and setup the files for you.

**Comment by rachanakushwaha** [comment]
Thanks @robinguptaprovar

**Comment by smilinrobin** [comment]
@rachanakushwaha - Hello . The issue for "testzeus.base not found" should be resolved now as we have : 

1. Updated the folder structures for both TestZeus Maven dependency and the corresponding framework. 
2. Cleaned up Base Test class
3. Updated the TestZeus maven dependency version to 1.0.2

If you would simply like to fix the issue, you can just update the maven dependency version for TestZeus to 1.0.2 in your POM file. Alternatively, you can pull a new copy of the framework itself from [here](https://github.com/TestZeus/TestZeus)
Can you please try it out and let us know of your feedback ?
